apiVersion: v1
kind: Pod
metadata:
  name: dind
spec:
  containers:
    - name: kubectl
      image: joshendriks/alpine-k8s
      command: 
      - /bin/cat
      tty: true
    - name: docker-cmds
      image: docker:1.12.6
      env:
        - name: DOCKER_HOST
          value: tcp://localhost:2375
    - name: dind-daemon
      image: docker:1.12.6-dind
      securityContext:
        privileged: true
      volumeMounts:
        - name: docker-graph-storage
          mountPath: /var/lib/docker
  volumes:
    - name: docker-graph-storage
      emptyDir: {}
