apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: prod 
  labels:
    app: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: oratar333/dotnet_app:<TAG>
          ports:
            - containerPort: 80
