apiVersion: v1
kind: Pod
metadata:
  name: jenkins
  namespace: devops
  labels:
    app: jenkins
spec:
  securityContext:
    fsGroup: 1000
    runAsUser: 1000
  serviceAccountName: jenkins-admin
  containers:
    - name: jenkins
      image: jenkins/jenkins:lts
      ports:
        - name: httpport
          containerPort: 8080
        - name: jnlpport
          containerPort: 50000
      volumeMounts:
        - name: jenkins-data
          mountPath: /var/jenkins_home
  volumes:
    - name: jenkins-data
      persistentVolumeClaim:
        claimName: jenkins-pv-claim

