apiVersion: v1
kind: Pod
metadata:
  name: jenkins
  namespace: devops
  labels:
    name: jenkins  
spec:
  containers:
  - name: jenkins
    image: jenkins/jenkins:lts-jdk11
    ports:
    - containerPort: 8080
    volumeMounts:
    - name: jenkins-home
      mountPath: /jenkins_home
  volumes:
  - name: jenkins-home
    hostPath:
      path: /var/jenkins_home

